### ISSUE TITLE
xvfb broken

### ISSUE THREAD

**Issue by jonashaag** [jonashaag/django-addanother#33]
@jpic can you have a look at the xvfb parts of the tests, they seem broken I have no idea how it works

**Comment by jonashaag** [comment]
@jpic

**Comment by jpic** [comment]
Where do you see it ?

I just found 
```
  File "/home/travis/build/jonashaag/django-addanother/test_project/testapp/models.py", line 12, in <module>

    class Player(models.Model):

  File "/home/travis/build/jonashaag/django-addanother/test_project/testapp/models.py", line 17, in Player

    help_text='This demonstrates the wrapper adding an "add" button only'

TypeError: __init__() missing 1 required positional argument: 'on_delete'

```

**Comment by jonashaag** [comment]
https://travis-ci.org/jonashaag/django-addanother/jobs/622692833

**Comment by jpic** [comment]
> E                       WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

I think it wants some package to be installed

**Comment by jpic** [comment]
There are dirty solutions out there on internet (downloading a fixed release number for geckodriver)
I'm looking for better solutions before going for that
Pushing into `travis` branch, will open PR when I find a nice solution or have eliminated all of them and resigned to dirty solution
Thanks for reaching out Jonas

**Comment by jonashaag** [comment]
@jpic any news here? Otherwise I will disable these tests for now

**Comment by jpic** [comment]
I could fix geckdriver in
https://github.com/jonashaag/django-addanother/pull/38

There are a number of other problems failing tests, for example Python 2.7,
it seems support was dropped in master (metaclass= usage).

Python 3.4 doesn't work in travis anymore:

Downloading archive:
https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/18.04/x86_64/python-3.4.tar.bz2
0.04s$ curl -sSf --retry 5 -o python-3.4.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 404
Unable to download 3.4 archive. The archive may not exist. Please consider
a different version.

Overall it runs a lot of jobs, if we keep in mind that Travis is a free
service that is shared amongst all projects we should aim at being good
neighbours: try to cut that number, run latest python on latest django, and
then some combinations of older versions, unless having each and every
combination turned out to be more useful than not so far for you.

**Comment by jpic** [comment]
Good news, we have two passed, Django 1.11 on Python 3.5 and Python 3.6:
https://travis-ci.org/github/jonashaag/django-addanother/builds/672430778

Can you take it from here?

**Comment by jonashaag** [comment]
Great, thanks!

Yes we should reduce number of jobs
